/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RutinasRouteImport } from './routes/rutinas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RutinasIdRouteImport } from './routes/rutinas.$id'

const RutinasRoute = RutinasRouteImport.update({
  id: '/rutinas',
  path: '/rutinas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutinasIdRoute = RutinasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RutinasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rutinas': typeof RutinasRouteWithChildren
  '/rutinas/$id': typeof RutinasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rutinas': typeof RutinasRouteWithChildren
  '/rutinas/$id': typeof RutinasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rutinas': typeof RutinasRouteWithChildren
  '/rutinas/$id': typeof RutinasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rutinas' | '/rutinas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rutinas' | '/rutinas/$id'
  id: '__root__' | '/' | '/rutinas' | '/rutinas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RutinasRoute: typeof RutinasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rutinas': {
      id: '/rutinas'
      path: '/rutinas'
      fullPath: '/rutinas'
      preLoaderRoute: typeof RutinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutinas/$id': {
      id: '/rutinas/$id'
      path: '/$id'
      fullPath: '/rutinas/$id'
      preLoaderRoute: typeof RutinasIdRouteImport
      parentRoute: typeof RutinasRoute
    }
  }
}

interface RutinasRouteChildren {
  RutinasIdRoute: typeof RutinasIdRoute
}

const RutinasRouteChildren: RutinasRouteChildren = {
  RutinasIdRoute: RutinasIdRoute,
}

const RutinasRouteWithChildren =
  RutinasRoute._addFileChildren(RutinasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RutinasRoute: RutinasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
